image: alpine

stages:
  - build
  - test

# build advent itself
binary:
  stage: build
  before_script:
    - apk update
    - apk add make gcc musl-dev
  script: 
    - make advent
  artifacts:
    paths:
      - advent
  # cache outputs to reduce the build time
  cache:
    paths:
      - "*.o"

manpage:
  stage: build
  before_script:
    - apk update
    - apk add make asciidoc
  script:
    - make .asc.6
  artifacts:
    paths:
      - advent.6

html:
  stage: build
  before_script:
    - apk update
    - apk add make asciidoc libxslt
  script:
    - make .asc.html
  artifacts:
    paths:
      - advent.html

# run tests using the binary built before
test:
  stage: test
  before_script:
    - apk update
    - apk add make
  script:
    - cd tests
    - make
